#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2017 sboynton <sboynton@C02SG09NG8WQ-sboynton>
#
# Distributed under terms of the MIT license.

"""
A dictionary of stat abbreviations to the stat IDs used in the stat_categories dict
"""

stat_names = {
        "first_down" : "1D",
        "fourth_down_att" : "Att4D",
        "fourth_down_conv" : "Conv4D",
        "fourth_down_failed" : "Fail4D",
        "passing_first_down" : "Pass1D",
        "penalty" : "Pen",
        "penalty_first_down" : "Pen1D",
        "penalty_yds" : "PenYds",
        "rushing_first_down" : "Rush1D",
        "third_down_att" : "Att3D",
        "third_down_conv" : "Conv3D",
        "third_down_failed" : "Fail3D",
        "timeout" : "TO",
        "xp_aborted" : "XPAb",
        "defense_ast" : "DefAst",
        "defense_ffum" : "DefFFum",
        "defense_fgblk" : "DefFGBlk",
        "defense_frec" : "DefFRec",
        "defense_frec_tds" : "DefFRecTDs",
        "defense_frec_yds" : "DefFRecYds",
        "defense_int" : "DefInt",
        "defense_int_tds" : "DefIntTDs",
        "defense_int_yds" : "DefIntYds",
        "defense_misc_tds" : "DefMiscTDs",
        "defense_misc_yds" : "DefMiscYds",
        "defense_pass_def" : "DefPassDef",
        "defense_puntblk" : "DefPuntBlk",
        "defense_qbhit" : "DefQBHit",
        "defense_safe" : "DefSafe",
        "defense_sk" : "DefSk",
        "defense_sk_yds" : "DefSkYds",
        "defense_tkl" : "DefTkl",
        "defense_tkl_loss" : "DefTklL",
        "defense_tkl_loss_yds" : "DefTklLYds",
        "defense_tkl_primary" : "DefTklPrim",
        "defense_xpblk" : "DefXPBlk",
        "fumbles_forced" : "FFum",
        "fumbles_lost" : "LFum",
        "fumbles_notforced" : "NFFum",
        "fumbles_oob" : "OOBFum",
        "fumbles_rec" : "FumRec",
        "fumbles_rec_tds" : "FumRecTDs",
        "fumbles_rec_yds" : "FumRecYds",
        "fumbles_tot" : "FumTot",
        "kicking_all_yds" : "KickYds",
        "kicking_downed" : "KickDn",
        "kicking_fga" : "KickFGAtt",
        "kicking_fgb" : "KickFGBlkd",
        "kicking_fgm" : "KickFG",
        "kicking_fgm_yds" : "KickFGYds",
        "kicking_fgmissed" : "KickFGMiss",
        "kicking_fgmissed_yds" : "KickFGMissYds",
        "kicking_i20" : "KickIn20",
        "kicking_rec" : "KickRec",
        "kicking_rec_tds" : "KickRecTDs",
        "kicking_tot" : "KickTot",
        "kicking_touchback" : "KickTB",
        "kicking_xpa" : "KickXPAtt",
        "kicking_xpb" : "KickXPBlkd",
        "kicking_xpmade" : "KickXP",
        "kicking_xpmissed" : "KickXPMiss",
        "kicking_yds" : "KickYds",
        "kickret_fair" : "KickRetFair",
        "kickret_oob" : "KickRetOOB",
        "kickret_ret" : "KickRet",
        "kickret_tds" : "KickRetTDs",
        "kickret_touchback" : "KickRetTB",
        "kickret_yds" : "KickRetYds",
        "passing_att" : "PassAtt",
        "passing_cmp" : "PassCmp",
        "passing_cmp_air_yds" : "PassCmpAirYds",
        "passing_incmp" : "PassIncmp",
        "passing_incmp_air_yds" : "PassIncmpAirYds",
        "passing_int" : "PassInt",
        "passing_sk" : "PassSk",
        "passing_sk_yds" : "PassSkYds",
        "passing_tds" : "PassTDs",
        "passing_twopta" : "Pass2PtAtt",
        "passing_twoptm" : "Pass2Pt",
        "passing_twoptmissed" : "Pass2PtMiss",
        "passing_yds" : "PassYds",
        "punting_blk" : "PuntBlk",
        "punting_i20" : "PuntIn20",
        "punting_tot" : "PuntTot",
        "punting_touchback" : "PuntTB",
        "punting_yds" : "PuntYds",
        "puntret_downed" : "PuntRetDn",
        "puntret_fair" : "PuntRetFair",
        "puntret_oob" : "PuntRetOOB",
        "puntret_tds" : "PuntRetTDs",
        "puntret_tot" : "PuntRetTot",
        "puntret_touchback" : "PuntRetTB",
        "puntret_yds" : "PuntRetYds",
        "receiving_rec" : "Rec",
        "receiving_tar" : "RecTgt",
        "receiving_tds" : "RecTDs",
        "receiving_twopta" : "Rec2PtAtt",
        "receiving_twoptm" : "Rec2Pt",
        "receiving_twoptmissed" : "Rec2PtMiss",
        "receiving_yac_yds" : "RecYACYds",
        "receiving_yds" : "RecYds",
        "rushing_att" : "RushTot",
        "rushing_loss" : "RushL",
        "rushing_loss_yds" : "RushLYds",
        "rushing_tds" : "RushTDs",
        "rushing_twopta" : "Rush2PtAtt",
        "rushing_twoptm" : "Rush2Pt",
        "rushing_twoptmissed" : "Rush2PtMiss",
        "rushing_yds" : "RushYds",
        }
